### PR TITLE
Reenable tests

### PR DESCRIPTION
**Pull request by rawagner**
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by rawagner** [comment]
@GeetikaBatra the tests are now passing, i had to add script to the PR check job which installs node on slave.

**Comment by GeetikaBatra** [comment]
@rawagner, Please rebase this branch. Thanks in advance. :)

**Comment by rawagner** [comment]
@GeetikaBatra rebased

**Comment by GeetikaBatra** [comment]
Works perfectly, merging it :)

**Pull request merged**
