### PR TITLE
JBIDE-26914: update unit tests according removal of openshift.io

### PR DESCRIPTION
**Pull request by jeffmaury**
Signed-off-by: Jeff MAURY <jmaury@redhat.com>

### CODE REVIEW

**Comment by jeffmaury** [comment]
testPR

**Comment by jeffmaury** [comment]
testPR

**Comment by odockal** [comment]
@jeffmaury @sbouchet We probably need to get rights to this repo. who's the owner of the repo or org?

**Comment by jeffmaury** [comment]
Trying to find but did not find the answer yet. @ljelinkova ? @rawagner

**Comment by odockal** [comment]
Maybe @tisnik  could help us.

**Pull request merged**
