### PR TITLE
LSP Stream provider asks for osio token if we do not have it. Fixes #146

### LINKED ISSUE #146: LSP connection provider throws exception when token is null
https://github.com/fabric8-analytics/fabric8-analytics-devstudio-plugin/blob/master/plugins/com.redhat.fabric8analytics.lsp.eclipse.ui/src/com/redhat/fabric8analytics/lsp/eclipse/ui/Fabric8AnalyticsStreamConnectionProvider.java#L115

the condition should be the opposite -> if(token == null)

### PR DESCRIPTION
**Pull request by rawagner**
Signed-off-by: Rastislav Wagner <rawagner@redhat.com>

### CODE REVIEW

**Comment by GeetikaBatra** [comment]
@rawagner, the token is refreshed every 24 hours. ```Fabric8AnalysisPreferences.getInstance().getToken();``` stores the token only for the first time. I am checking if this token already exists, then get the refreshed new token from ```token = TokenCheck.getInstance().getToken();```. if user has not at all logged in, getting token from ```token = TokenCheck.getInstance().getToken()``` this will open the login window, directly, which will hinder user experience.

**Comment by rawagner** [comment]
Thanks for the explanation, i get the logic now :) 
So refreshing a token does not require to open a webpage and login again ? It happens automatically without need for user to input his username/pass again? If yes, does this work even if we want to refresh, lets say,  week old token ?

**Comment by GeetikaBatra** [comment]
The Login page opens only for the first time, for subsequent calls to ```token = TokenCheck.getInstance().getToken();``` will return the refreshed token. I am not sure about week old token, what it does is uses the current token and then retrieves a new token on the basis of old token information. I have never tested it with week old token. This is implemented here https://github.com/jbosstools/jbosstools-openshift/tree/master/plugins/org.jboss.tools.openshift.io.ui/src/main/java/org/jboss/tools/openshift/io/internal/ui

**Comment by jeffmaury** [comment]
Tokens are refreshed every day by the JBossTools OSIO module each time you request a token

**Pull request closed without merging**
