### PR TITLE
Replaced print statements to log statements

### PR DESCRIPTION
**Pull request by GeetikaBatra**

### CODE REVIEW

**Comment by rawagner** [comment]
@GeetikaBatra you need to to rebase your branch to master in order to remove b58f42fe776069926d89efec57ec85af7798cafb commit which is already pushed

**Comment by GeetikaBatra** [comment]
@rawagner, I have rebased the branch, Please review it and merge if necessary.

**Comment by rawagner** [comment]
testPR

**Comment by rawagner** [comment]
@GeetikaBatra there is a compliation error

**Comment by GeetikaBatra** [comment]
@rawagner, I have fixed the compile errors. Please merge it. Thanks in advance. :)

**Comment by rawagner** [comment]
LGTM!

**Pull request merged**
